export default[
    {
        cedula: 12345678,
        nombres: "Abcde",
        apellidos: "Abcde",
        fechaNacimiento: "1990-05-15",
        email: "email@email.com",
        telefono: "099999999",
        direccion: "sucasa",
        sexo: "Masculino",
        fechaDeIngreso: "2020-05-05",
        fechaDeEgreso: "",
        activo: true,
        fechaVencimientoCarnetDeSalud: "2030-05-05",
        fechaVencimientoCarnetBromatologia: "",
        carnetDeVacunas: true,
        cursos: {
            IdDocumento: 1,
            CedulaPersonal: 12345678,
            esCurso: true,
            NombreDocumento: "un curso",
            rutaDocumento: "una ruta",
            descripcion: "una desc"
        }
    },
    {
        cedula: 12345679,
        nombres: "qwe",
        apellidos: "qwe",
        fechaNacimiento: "1990-05-15",
        email: "email@email.com",
        telefono: "099999999",
        direccion: "sucasa",
        sexo: "fememinX",
        fechaDeIngreso: "2020-05-05",
        fechaDeEgreso: "",
        activo: true,
        fechaVencimientoCarnetDeSalud: "2020-05-05",
        fechaVencimientoCarnetBromatologia: "",
        carnetDeVacunas: true,
        cursos: {
            IdDocumento: 3,
            CedulaPersonal: 12345679,
            esCurso: true,
            NombreDocumento: "un curso",
            rutaDocumento: "una ruta",
            descripcion: "una desc"
        }
    },
    {
        cedula: 12345677,
        nombres: "EWQ",
        apellidos: "QWEQWE",
        fechaNacimiento: "1990-05-15",
        email: "email@email.com",
        telefono: "099999999",
        direccion: "sucasa",
        sexo: "Masculino",
        fechaDeIngreso: "2020-05-05",
        fechaDeEgreso: "",
        activo: true,
        fechaVencimientoCarnetDeSalud: "2030-05-05",
        fechaVencimientoCarnetBromatologia: "",
        carnetDeVacunas: true,
        cursos: {
            IdDocumento: 2,
            CedulaPersonal: 12345677,
            esCurso: true,
            NombreDocumento: "un curso",
            rutaDocumento: "una ruta",
            descripcion: "una desc"
        }
    },
    {
        cedula: 12345687,
        nombres: "Abcde",
        apellidos: "Abcde",
        fechaNacimiento: "1990-05-15",
        email: "email@email.com",
        telefono: "099999999",
        direccion: "sucasa",
        sexo: "Masculino",
        fechaDeIngreso: "2020-05-05",
        fechaDeEgreso: "",
        activo: true,
        fechaVencimientoCarnetDeSalud: "2030-05-05",
        fechaVencimientoCarnetBromatologia: "",
        carnetDeVacunas: true,
        cursos: {
            IdDocumento: 4,
            CedulaPersonal: 12345687,
            esCurso: true,
            NombreDocumento: "un curso",
            rutaDocumento: "una ruta",
            descripcion: "una desc"
        }
    },
    {
        cedula: 12345654,
        nombres: "otro",
        apellidos: "Abcde",
        fechaNacimiento: "1990-05-15",
        email: "email@email.com",
        telefono: "099999999",
        direccion: "sucasa",
        sexo: "Masculino",
        fechaDeIngreso: "2020-05-05",
        fechaDeEgreso: "",
        activo: true,
        fechaVencimientoCarnetDeSalud: "2010-05-05",
        fechaVencimientoCarnetBromatologia: "2010-05-05",
        carnetDeVacunas: true,
        cursos: {
            IdDocumento: 5,
            CedulaPersonal: 12345654,
            esCurso: true,
            NombreDocumento: "un curso",
            rutaDocumento: "una ruta",
            descripcion: "una desc"
        }
    },
    {
        cedula: 87654321,
        nombres: "Abcde",
        apellidos: "Abcde",
        fechaNacimiento: "1990-05-15",
        email: "email@email.com",
        telefono: "099999999",
        direccion: "sucasa",
        sexo: "Masculino",
        fechaDeIngreso: "2020-05-05",
        fechaDeEgreso: "",
        activo: true,
        fechaVencimientoCarnetDeSalud: "2030-05-05",
        fechaVencimientoCarnetBromatologia: "2030-05-05",
        carnetDeVacunas: true,
        cursos: {
            IdDocumento: 6,
            CedulaPersonal: 87654321,
            esCurso: true,
            NombreDocumento: "un curso",
            rutaDocumento: "una ruta",
            descripcion: "una desc"
        }
    },
    {
        cedula: 45698732,
        nombres: "Abcde",
        apellidos: "Abcde",
        fechaNacimiento: "1990-05-15",
        email: "email@email.com",
        telefono: "099999999",
        direccion: "sucasa",
        sexo: "Masculino",
        fechaDeIngreso: "2020-05-05",
        fechaDeEgreso: "",
        activo: true,
        fechaVencimientoCarnetDeSalud: "2030-05-05",
        fechaVencimientoCarnetBromatologia: "2030-05-05",
        carnetDeVacunas: true,
        cursos: {
            IdDocumento: 7,
            CedulaPersonal: 45698732,
            esCurso: true,
            NombreDocumento: "un curso",
            rutaDocumento: "una ruta",
            descripcion: "una desc"
        }
    },

]